" Vim configuration file
" Created by Mateo Chavez: mateo.chavez.esp@gmail.com

" Screw vi compatibility
set nocompatible

" Plugin manager
execute pathogen#infect()

" Some cool stuff
syntax on
filetype plugin indent on

set number
set relativenumber
set tabstop=4
set expandtab
set cc=80

" Show trailing white space
set list
set listchars=tab:>-,trail:-


" -----------------------------------------------------
" Fuzzy finder behavior
"------------------------------------------------------

" Search down into sub-folders when using find
" Provides tab-completion for all file-related tasks
set path+=**

" Display all posibilities when using find and a wildcharacter
" to search files
set wildmenu


" -----------------------------------------------------
" Grep configuration
"------------------------------------------------------
set grepprg=grep\ -n\ $*
nmap gø :grep -R -H <cword> --include=*.{py,txt,sh,c,h}<cr> :copen<cr>
nmap ø :cn<cr>
nmap æ :cp<cr>
nmap ggø :cclose<cr>


" -----------------------------------------------------
" Tag jumping
"------------------------------------------------------
command! MakeTags !ctags -R .


" -----------------------------------------------------
" Key mapping
"------------------------------------------------------

" Tab management
map ↓ :tabr <cr>
map π :tabl <cr>
map → :tabp <cr>
map œ :tabn <cr>

map <tab> :tabfind
map 0<tab> 0gt
map 1<tab> 1gt
map 2<tab> 2gt
map 3<tab> 3gt
map 4<tab> 4gt
map 5<tab> 5gt
map 6<tab> 6gt
map 7<tab> 7gt
map 8<tab> 8gt
map 9<tab> 9gt

